samples/Sample_05_Chart.php
src/PhpPowerpoint/Shape/Chart/Series.php
src/PhpPowerpoint/Shape/Chart/Type/Bar.php
src/PhpPowerpoint/Shape/Chart/Type/Bar3D.php
src/PhpPowerpoint/Shape/Chart/Type/Pie.php
src/PhpPowerpoint/Writer/ODPresentation/ObjectsChart.php
src/PhpPowerpoint/Writer/PowerPoint2007/Chart.php
tests/PhpPowerpoint/Tests/Shape/Chart/Type/Bar3DTest.php
tests/PhpPowerpoint/Tests/Shape/Chart/Type/BarTest.php
tests/PhpPowerpoint/Tests/Shape/Chart/Type/PieTest.php
tests/PhpPowerpoint/Tests/Writer/ODPresentation/ChartsTest.php
tests/PhpPowerpoint/Tests/Writer/PowerPoint2007/ChartTest.php

Add Non 3D Pie Chart Type
Add Grouping Option to Bar Charts - To allow for Stack and Percent Stacked Charts

Add Pie Chart Type & Stack Percent Bar Charts

---

README.md

I noticed that the build status logo was referring to an old(?) travis link.

Fix Build Status logo in README.md

---

src/PhpPresentation/Style/Color.php
src/PhpPresentation/Writer/PowerPoint2007/AbstractDecoratorWriter.php

These changes add support for alpha channel on fill colours addressing this issue; #201 
If there's anything I can do better, let me know!

Implement alpha channel to Fills 

---

src/PhpPresentation/Slide.php
src/PhpPresentation/Slide/Animation.php
src/PhpPresentation/Writer/PowerPoint2007/PptSlides.php

Updated for latest dev branch
Previous : #178

Adding animations

---

CHANGELOG.md
src/PhpPresentation/Style/Font.php
src/PhpPresentation/Writer/PowerPoint2007/PptSlides.php
tests/PhpPresentation/Tests/Style/FontTest.php
tests/PhpPresentation/Tests/Writer/PowerPoint2007/PptSlidesTest.php

Hello,
This small piece of code allows you to add character spacing to your text. Simply use the setter:
`setCSpacing($pValue);`
Where the value is given in pts.
Example:
```
$oText = $currentSlide->createRichTextShape()
$oTextRun = $oText->createTextRun('Text with character spacing.');
$oTextRun->getFont()->setCSpacing(0.5);
```

Implement character spacing

---

src/PhpPresentation/Reader/ODPresentation.php

Sometimes 
```php
$this->arrayStyles[$keyStyle]['listStyle']
```
is empty but 
```php
$this->arrayStyles[$keyStyle]
```
is set. So it leads to an undefined offset error.

fix arraystyles being empty

---

src/PhpPresentation/Style/Alignment.php
src/PhpPresentation/Writer/PowerPoint2007/PptSlides.php

This PR allows setting bottom and top margins, and propagates those margins (as well as left and right) when serializing table objects.
I think this would cover what is requested in #273.

Allow setting top and bottom margins, write table margins in PPTX writer

---

src/PhpPresentation/Writer/AbstractWriter.php
src/PhpPresentation/Writer/PowerPoint2007/AbstractSlide.php
src/PhpPresentation/Writer/PowerPoint2007/PptSlideMasters.php
tests/PhpPresentation/Tests/Writer/AbstractWriter.php
tests/PhpPresentation/Tests/Writer/AbstractWriterTest.php
tests/PhpPresentation/Tests/Writer/PowerPoint2007/PptSlideMastersTest.php

Fixes bugs in saving master slides:
- draw shapes are not included in data written, because only shapes from regular slides are iterated over
- IDs used in relationship files linking powerpoint master slides to media are doubles - which leads to "broken" images when opening powerpoint files and PowerPoint 2010+ trying to repair the files
- background images in masterslides are neither written nor linked

Bugfixes for masterslide issues: issue #330, problems with broken powerpoints needing repair, missing images in shapes

---

src/PhpPresentation/Writer/PowerPoint2007/PptCharts.php

tempnam() creates a file that is not removed. Only $pFilename . '.xlsx' is removed by $this->writeSpreadsheet().

Remove temp file

---

samples/Sample_Header.php

the casing didn't match the case of the folder names.
the vendor autoload is in a different folder...

problems accessing files

---

tests/PhpPresentation/Tests/PhpPresentationTest.php
tests/PhpPresentation/Tests/Shape/RichText/ParagraphTest.php
tests/PhpPresentation/Tests/Writer/AbstractWriterTest.php
tests/PhpPresentation/Tests/_includes/PhpPresentationTestCase.php

I've refactored some tests using `PHPUnit` assertion methods, instead of `PHP`'s. This will give us better error messages in case of failure.

Refactoring tests

---

src/PhpPresentation/Shape/Group.php
tests/PhpPresentation/Tests/Shape/GroupTest.php

Previously the group extents where calculated based on the extents of the containing shapes, which uses  the slide/container of the group as the point of reference. This would result in the group being larger than
needed; especially noticeable for a large X or Y offset.
Example selected group in PowerPoint 2016 before these changes:
The same example and selection after the code changes:
The code that generated the above two files was a slight modification of `samples/Sample_08_Group.php` to move the first image further away from the left and top so as to more clearly show the effect:
```php
<?php
include_once 'Sample_Header.php';
use PhpOffice\PhpPresentation\PhpPresentation;
use PhpOffice\PhpPresentation\Style\Alignment;
use PhpOffice\PhpPresentation\Style\Color;
// Create new …
```

Change group shape extents to reflect content width/height.

---

src/PhpPresentation/Writer/PowerPoint2007/PptCharts.php
tests/PhpPresentation/Tests/Writer/PowerPoint2007/PptChartsTest.php
tests/resources/schema/ooxml/dml-chart.xsd

I have removed two instances of % signs in PptCharts which cause presentations with charts to be corrupted on newer versions of Powerpoint. I have also updated the test suite to match. 
However I am unsure if the changes I've made to the test schema are acceptable. Please let me know and I can updated.
Fixes issue #452 and possibly a couple others.

Remove % signs from PptCharts to fix chart generation. Fixes #452

---

composer.json

`ext-gd2` is  not recognized by composer and should instead be `ext-gd`.

Use proper name for `ext-gd`

---

.travis.yml
CHANGELOG.md
phpmd.xml.dist

Fixes #543 and the develop build.

Drop the support for HHVM

---

CHANGELOG.md
samples/Sample_Header.php
src/PhpPresentation/Reader/PowerPoint2007.php

Hello @Progi1984, I added hyperlinks to pictures using PowerPoint. When I tried to read them using your awesome library, the hyperlinks were not showing up. Turns out, they were not being parsed. This PR adds support and actually extends #49. Please let me know what can I do to make this PR better. Thanks!

Add hyperlink parsing under pictures

---

CHANGELOG.md
src/PhpPresentation/Reader/PowerPoint2007.php

Load PowerPoint 2007 images converted all files to png.
It's only default used.
I'm changed mimeType and renderingFunction.

PowerPoint2007 Reader : Load images in their initial format (and not by default in PNG)

---

CHANGELOG.md
src/PhpPresentation/Shape/AbstractGraphic.php

Add zero check before divizion

Defining width & height of a shape don't return any error if width & height were equal to 0

---

.travis.yml

fix all PHP5 travis builds erroring while composer install memory exhaustion

Fix travis composer install memory exhaustion issue

---

src/PhpPresentation/Writer/AbstractWriter.php
src/PhpPresentation/Writer/PowerPoint2007/PptSlideLayouts.php

This pull request adds drawings and background images to slide layouts.

Add drawings and background images to slide layouts

---

src/PhpPresentation/Writer/PowerPoint2007/ContentTypes.php

Due to the change https://github.com/PHPOffice/PHPPresentation/pull/637 we get an error with SlideLayouts:
`PhpOffice\PhpPresentation\Slide\AbstractSlide::getRelsIndex(): Return value must be of type string, null returned.`
It seems that `relsIndex` is not set for SlideLayouts and remains null. By adjusting the return type it does not work now. The method is used in:
`PhpOffice\PhpPresentation\Writer\PowerPoint2007\PptSlideLayouts::67`
It can be fixed by setting `relsIndex` in 
`PhpOffice\PhpPresentation\Writer\PowerPoint2007\ContentTypes::75`

Set rels index for slide layouts

---

docs/changes/1.0.0.md
docs/changes/1.1.0.md
docs/usage/shapes/richtext.md
mkdocs.yml
src/PhpPresentation/Reader/PowerPoint2007.php
src/PhpPresentation/Shape/Hyperlink.php
src/PhpPresentation/Writer/PowerPoint2007/AbstractSlide.php
tests/PhpPresentation/Tests/Reader/PowerPoint2007Test.php
tests/PhpPresentation/Tests/Shape/HyperlinkTest.php
tests/PhpPresentation/Tests/Writer/PowerPoint2007/PptSlidesTest.php

Hyperlinks can now be set to use the text color instead of the default theme color. This way it becomes possible to actually set the hyperlink color when using PowerPoint2007 writer.
Fixes #541
```
$textRun->getHyperlink()->setUrl($url);
$textRun->getHyperlink()->setUseTextColor(true);
```

Fix: Hyperlink text color for PowerPoint2007 writer

---

docs/changes/1.0.0.md
docs/changes/1.1.0.md
docs/usage/shapes/chart.md
src/PhpPresentation/Shape/Chart/Axis.php
src/PhpPresentation/Writer/PowerPoint2007/PptCharts.php
tests/PhpPresentation/Tests/Shape/Chart/AxisTest.php
tests/PhpPresentation/Tests/Writer/PowerPoint2007/PptChartsTest.php

- adds crosses/ crossesAt options to axis component
- adds reversed order to axis component

Support for axis options (Intersection Point & Reverse Axis) in PowerPoint2007 Writer

---

docs/changes/1.1.0.md
src/PhpPresentation/Shape/Chart/Axis.php
tests/PhpPresentation/Tests/Shape/Chart/AxisTest.php

Superseeds #761 by @WFarmerEthisphere

Fixed broken powerpoint presentations due to MS Office update 2309

---

docs/changes/1.1.0.md
src/PhpPresentation/Writer/PowerPoint2007/PptCharts.php
tests/PhpPresentation/Tests/Writer/PowerPoint2007/PptChartsTest.php

Superseeds #754 by @LilyEssence

PowerPoint2077 Writer : Fixed error when defining min/max bounds to 0

---

docs/changes/1.1.0.md
src/PhpPresentation/Shape/Chart/Type/AbstractTypeBar.php
src/PhpPresentation/Shape/Chart/Type/AbstractTypeLine.php
src/PhpPresentation/Shape/Chart/Type/AbstractTypePie.php
src/PhpPresentation/Writer/PowerPoint2007/PptCharts.php
tests/PhpPresentation/Tests/Writer/PowerPoint2007/PptChartsTest.php
tests/PhpPresentation/Tests/_includes/PhpPresentationTestCase.php

Superseeds #664 by @michael-roth

PowerPoint2007 Writer : Fixed column indices for embedded spreadsheets

---

docs/changes/1.1.0.md
src/PhpPresentation/Writer/PowerPoint2007/AbstractSlide.php
tests/PhpPresentation/Tests/Writer/PowerPoint2007/PptSlidesTest.php
tests/PhpPresentation/Tests/_includes/PhpPresentationTestCase.php

This fixes the broken relationship reference for video files as described in #681. Videos will work with this patch, but no thumbnail is displayed when the videos is stopped. (This would require thumbnail creation and another relationship for the thumbnail image.)
Superseeds #697 by @potofcoffee
Fixes #681

PowerPoint2007 Writer : Fixed broken video file relationship

---

docs/changes/1.1.0.md
src/PhpPresentation/Slide.php

Raised max value for identifier rand call

---

docs/changes/1.1.0.md
src/PhpPresentation/Writer/PowerPoint2007/AbstractSlide.php
tests/PhpPresentation/Tests/Writer/PowerPoint2007/PptSlidesTest.php

Superseeds #464 by @shannan1989
Fixes #446 by @williammck & @Aggiekev

PowerPoint2007 Writer : Fixed broken animation for first shape

---

docs/changes/1.1.0.md
samples/Sample_Header.php

Superseeds #609 by @pal-software

Samples : Allow to run without composer

---

docs/changes/1.1.0.md
src/PhpPresentation/PhpPresentation.php
tests/PhpPresentation/Tests/PhpPresentationTest.php

If in the original code you would add a dump of the slide collection like the example below and try to copy a presentation with three slides you'll get an exception:
> Undefined array key 2
The code:
```php
public function copy(): self
{
$copied = clone $this;
$slideCount = count($this->slideCollection);
for ($i = 0; $i < $slideCount; ++$i) {
var_dump(array_keys($this->slideCollection));
$this->slideCollection[$i] = $this->slideCollection[$i]->copy();
$this->slideCollection[$i]->rebindParent($this);
}
return $copied;
}
```
The dump output:
```
array:3 [ // vendor/phpoffice/phppresentation/src/PhpPresentation/PhpPresentation.php:325
0 => 0
1 => 1
2 => 2
]
array:2 [ // vendor/phpoffice/phppresentation/src/PhpPresentation/PhpPresentation.php:325
0 => 0
1 => 1
]
array:1 [ // …
```

General : Fixed copying bug when presentation had multiple slides

---

docs/changes/1.1.0.md
src/PhpPresentation/DocumentLayout.php
tests/PhpPresentation/Tests/DocumentLayoutTest.php

Fixes #722
Superseeds #611 by @jiangzhangchan

Core : DocumentLayout : Fixed error when using DocumentLayout::LAYOUT_CUSTOM

---

docs/changes/1.2.0.md
src/PhpPresentation/Reader/PowerPoint2007.php
src/PhpPresentation/Shape/RichText/Paragraph.php

Word2007 Reader: Fixed cast of spacing
Fixes #729 & Fixes #796

Word2007 Reader: Fixed cast of spacing

---

docs/changes/1.2.0.md
src/PhpPresentation/Shape/Group.php
tests/PhpPresentation/Tests/Shape/GroupTest.php

This pull requests modifies the Group container shape so moving it around moves all contained shapes with it.
To make this work reliably all offsets, extents and dimensions are calculated based on the contained shapes and not cached anymore.
I also fixed the Group writing part in the PowerPoint2007 writer which used the extentX/Y methods to get the width and height. (The XML nodes/attributes are named really misleading here)
Thank you for considering this contribution and thank you for your work!

Improve Group shape to allow moving all contained shapes at once.

---

composer.json

The sample is missing but it works.
There are also 3 Sample_12 files missing. But they do not work mainly because PhpPptTree does not exists.
If this is missing on purpose, just close this.
Fixes no issue.
None of the above, sorry.

Added Sample_02_Serialized to composer samples

---

.github/workflows/php.yml
composer.json
docs/changes/1.2.0.md

Added support for PHP 8.4 & `phpoffice/phpspreadsheet`: Allow version 3.0
Fixes #836

Added support for PHP 8.4 & `phpoffice/phpspreadsheet`: Allow version 3.0

---

docs/changes/1.2.0.md
phpstan.neon.dist
src/PhpPresentation/Reader/PowerPoint2007.php
src/PhpPresentation/Shape/Drawing/Gd.php

`Gd::setImageResource()` : Fixed when imagecreatetruecolor returns false

`Gd::setImageResource()` : Fixed when imagecreatetruecolor returns false

---

docs/changes/1.2.0.md
samples/Sample_05_Chart_Line.php
src/PhpPresentation/Writer/PowerPoint2007/PptCharts.php
tests/PhpPresentation/Tests/Writer/PowerPoint2007/PptChartsTest.php

Word2007 Writer: LineChart supports LabelPosition for Series
Fixes #606

Word2007 Writer: LineChart supports LabelPosition for Series

---

docs/changes/1.2.0.md
src/PhpPresentation/Traits/ShapeCollection.php
tests/PhpPresentation/Tests/Slide/AbstractSlideTest.php
tests/PhpPresentation/Tests/SlideTest.php
tests/PhpPresentation/Tests/Writer/PowerPoint2007/PptChartsTest.php

`createDrawingShape` has no container defined
Fixes #820

`createDrawingShape` has no container defined

---

docs/changes/1.2.0.md
samples/Sample_12_Reader_ODPresentation.php
src/PhpPresentation/Reader/ODPresentation.php
src/PhpPresentation/Shape/RichText/Paragraph.php
tests/PhpPresentation/Tests/Writer/PowerPoint2007/PptChartsTest.php

ODPresentation Reader : Read differents units for margin

---

composer.json
docs/changes/1.2.0.md
docs/index.md
docs/usage/writers.md
samples/Sample_01_Complex.php
samples/Sample_Header.php
src/PhpPresentation/AbstractShape.php
src/PhpPresentation/Exception/WriterPDFAdapterNotDefinedException.php
src/PhpPresentation/Shape/Media.php
src/PhpPresentation/Writer/AbstractWriter.php
src/PhpPresentation/Writer/HTML.php
src/PhpPresentation/Writer/PDF.php
src/PhpPresentation/Writer/PDF/DomPDF.php
src/PhpPresentation/Writer/PDF/PDFWriterInterface.php
tests/PhpPresentation/Tests/Shape/MediaTest.php
tests/PhpPresentation/Tests/Writer/AbstractWriterTest.php
tests/PhpPresentation/Tests/Writer/HTMLTest.php
tests/PhpPresentation/Tests/Writer/PDFTest.php

PDF/HTML Writer : Added support
- HTML
Fixes #221
Fixes #567
Fixes #644
- PDF
Fixes #181
Fixes #381
Fixes #472
Fixes #693
Fixes #725

PDF/HTML Writer : Added support

---

docs/changes/1.2.0.md
src/PhpPresentation/Style/TextStyle.php
tests/PhpPresentation/Tests/Style/TextStyleTest.php

PhpOffice\PhpPresentation\Style\TextStyle : Fixed typo for default indent

PhpOffice\PhpPresentation\Style\TextStyle : Fixed typo for default indent
