PHPOffice/PHPPresentation

- src/PhpPresentation/Writer/PowerPoint2007/LayoutPack/PackDefault.php
https://github.com/PHPOffice/PHPPresentation/issues/89
> Fix for opening and needing a repair on PC/Mac.

- CHANGELOG.md
- README.md
- docs/faq.rst
- src/PhpPresentation/Reader/PowerPoint2007.php
- src/PhpPresentation/Writer/PowerPoint2007/AbstractLayoutPack.php
- tests/PhpPresentation/Tests/Writer/PowerPoint2007/LayoutPack/TemplateBasedTest.php
> #127 : Documentation fixes after the rename

- CHANGELOG.md
- docs/index.rst
- docs/shapes.rst
- docs/shapes_comment.rst
- docs/shapes_richtext.rst
- src/PhpPresentation/Shape/RichText/BreakElement.php
- src/PhpPresentation/Shape/RichText/TextElement.php
- src/PhpPresentation/Shape/RichText/TextElementInterface.php
- src/PhpPresentation/Writer/ODPresentation/Content.php
- src/PhpPresentation/Writer/PowerPoint2007/PptSlides.php
- tests/PhpPresentation/Tests/Shape/RichText/BreakElementTest.php
- tests/PhpPresentation/Tests/Shape/RichText/RunTest.php
- tests/PhpPresentation/Tests/Shape/RichText/TextElementTest.php
- tests/PhpPresentation/Tests/Writer/ODPresentation/ContentTest.php
- tests/PhpPresentation/Tests/Writer/PowerPoint2007/PptSlidesTest.php
> #180 : Added language property to TextElement

- CHANGELOG.md
- docs/general.rst
- src/PhpPresentation/PhpPresentation.php
- src/PhpPresentation/PresentationProperties.php
- src/PhpPresentation/Writer/PowerPoint2007/PptViewProps.php
- tests/PhpPresentation/Tests/PhpPresentationTest.php
- tests/PhpPresentation/Tests/PresentationPropertiesTest.php
- tests/PhpPresentation/Tests/Writer/PowerPoint2007/PptViewPropsTest.php
> #120 : Presentation with predefined View Type

- CHANGELOG.md
- src/PhpPresentation/Style/Color.php
- src/PhpPresentation/Writer/PowerPoint2007/AbstractDecoratorWriter.php
- src/PhpPresentation/Writer/PowerPoint2007/PptCharts.php
- src/PhpPresentation/Writer/PowerPoint2007/PptSlides.php
- tests/PhpPresentation/Tests/Style/ColorTest.php
> #203 : Implement alpha channel to Fill

- README.md
- src/PhpPresentation/Shape/Line.php
- src/PhpPresentation/Writer/ODPresentation/Content.php
- tests/PhpPresentation/Tests/Slide/TransitionTest.php
- tests/PhpPresentation/Tests/Writer/ODPresentation/ObjectsChartTest.php
Installation instructions for manual installation now includes missing PHPOffice/Common information
> Include complete manual installation instructions

- CHANGELOG.md
- src/PhpPresentation/Writer/PowerPoint2007/PptCharts.php
- tests/PhpPresentation/Tests/Writer/PowerPoint2007/PptChartsTest.php
> #211 : Fixed the marker on line chart when symbol is none

- CHANGELOG.md
- samples/Sample_05_Chart.php
- src/PhpPresentation/Writer/PowerPoint2007/PptCharts.php
> #212 : Fixed the format value in Pie Chart

- CHANGELOG.md
- samples/Sample_05_Chart.php
- src/PhpPresentation/Writer/PowerPoint2007/PptCharts.php
- tests/PhpPresentation/Tests/Writer/PowerPoint2007/PptChartsTest.php
> #267 : Fixed the axis title in bar chart

- CHANGELOG.md
- samples/Sample_05_Chart.php
- src/PhpPresentation/Writer/PowerPoint2007/PptCharts.php
> #268 : Fixed the label position in bar chart

- src/PhpPresentation/Writer/PowerPoint2007/PptCharts.php
> #264 : "PHPExcel" file name is generated in the system's temporary directory.

- src/PhpPresentation/Reader/PowerPoint2007.php
- src/PhpPresentation/Writer/PowerPoint2007.php
@Progi1984 requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/PHPOffice/PHPPresentation/
> Scrutinizer Auto-Fixes

- src/PhpPresentation/Shape/Chart/Axis.php
- src/PhpPresentation/Writer/PowerPoint2007/PptCharts.php
This allows to hide an axis in ppt files.
You our contributing guide is 404 so I am pushing it as it is and hope for the best.
> Add Option to delete an axis.

- CHANGELOG.md
- docs/shapes_chart.rst
- samples/Sample_05_Chart.php
- src/PhpPresentation/Shape/Chart/Type/AbstractTypeBar.php
- src/PhpPresentation/Writer/PowerPoint2007/PptCharts.php
- tests/PhpPresentation/Tests/Shape/Chart/Type/Bar3DTest.php
- tests/PhpPresentation/Tests/Shape/Chart/Type/BarTest.php
- tests/PhpPresentation/Tests/Writer/PowerPoint2007/PptChartsTest.php
> #358 : PowerPoint2007 Writer : Implement gap width in Bar(3D) Charts

- CHANGELOG.md
- docs/shapes_table.rst
- samples/Sample_04_Table.php
- src/PhpPresentation/Writer/PowerPoint2007/AbstractSlide.php
- tests/PhpPresentation/Tests/Writer/PowerPoint2007/PptSlidesTest.php
> #347 : PowerPoint2007 Writer : Margins in table cell

- .github/workflows/php.yml
- docs/changes/1.0.0.md
**History:**
- 2021-07-29 : Wait for phpspec/prophecy#533 (for PHPUnit)
- 2021-08-23: PR Merged but not released
> Added support for PHP 8.1

- docs/writers.rst
Reverts PHPOffice/PHPPresentation#593
> Revert "Update writers.rst"

- docs/changes/1.1.0.md
- docs/usage/shapes/chart.md
- src/PhpPresentation/Shape/Chart/Axis.php
- src/PhpPresentation/Writer/PowerPoint2007/PptCharts.php
- tests/PhpPresentation/Tests/Shape/Chart/AxisTest.php
- tests/PhpPresentation/Tests/Writer/PowerPoint2007/PptChartsTest.php
> PowerPoint 2007 Writer : Added support to Font for Axis tick label & chinese font support

- docs/changes/1.1.0.md
- src/PhpPresentation/Writer/PowerPoint2007/PptSlides.php
Superseeds #692 by @DennisBirkholz
Fixes #691
> PowerPoint2007 Writer: Extract relations from nested ShapeContainerInterface objects

- docs/changes/1.2.0.md
- src/PhpPresentation/Reader/PowerPoint2007.php
Word2007 Reader: Fixed cast of color
Fixes #826
> Word2007 Reader: Fixed cast of color

- docs/changes/1.2.0.md
- docs/usage/shapes/autoshape.md
- src/PhpPresentation/Shape/Group.php
- src/PhpPresentation/Slide/AbstractSlide.php
- tests/PhpPresentation/Tests/Shape/GroupTest.php
- tests/PhpPresentation/Tests/Slide/AbstractSlideTest.php
`createAutoShape` : Add method to create geometric shapes
Superseeds #443 by @mhasanshahid
> `createAutoShape` : Add method to create geometric shapes

- docs/changes/1.2.0.md
- docs/usage/readers.md
- src/PhpPresentation/Reader/ODPresentation.php
- src/PhpPresentation/Reader/PowerPoint2007.php
- src/PhpPresentation/Reader/PowerPoint97.php
- src/PhpPresentation/Reader/ReaderInterface.php
- src/PhpPresentation/Reader/Serialized.php
- tests/PhpPresentation/Tests/Reader/ODPresentationTest.php
- tests/PhpPresentation/Tests/Reader/PowerPoint2007Test.php
- tests/PhpPresentation/Tests/Reader/PowerPoint97Test.php
> Reader : Option to not load images

- docs/changes/1.2.0.md
- samples/Sample_11_Shape.php
- samples/Sample_Header.php
- src/PhpPresentation/AbstractShape.php
- src/PhpPresentation/Writer/ODPresentation/Content.php
- src/PhpPresentation/Writer/PowerPoint2007/AbstractSlide.php
- tests/PhpPresentation/Tests/Writer/ODPresentation/ContentTest.php
> ODPresentation Writer : Support for rotation for RichText
